blank_issues_enabled: false
contact_links:
  - name: Read the community guidelines
    about: "Please make sure you have read the submission guidelines before posting an issue"
    url: https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-an-issue
  - name: Want to start a discussion?
    about: "Want to start a thread to discuss an idea? Use the discussions feature provided by GitHub."
    url: https://github.com/nrwl/nx/discussions
  - name: Have a question?
    url: https://go.nrwl.io/join-slack
    about: "The Community Slack is a great place for questions to be asked and answered. Please use the #support channel if you need help with your workspace!"
  - name: Are you looking for integration with a new tool?
    url: https://nx.dev/community
    about: "There are a lot of awesome Plugins for Nx provided by the community! Check here to see if there is a community plugin to integrate your tool."
